name: myst
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.*
  - jupyter
  - sphinx
  - pydata-sphinx-theme
  - ghp-import
  - nbsphinx
  - pip
  - pip:
    - git+https://github.com/ExecutableBookProject/MyST-NB.git
    - jupyter-cache[cli]
    - git+https://github.com/mwouts/jupytext.git
    
    
